### PR TITLE
Bug fix 1778

### PR DESCRIPTION
**Pull request by UQAM-VIVO**
Correction of [https://jira.lyrasis.org/browse/VIVO-1778 ](url)
i18n: Only include one language per language directory

### CODE REVIEW

**Comment by awoods** [comment]
In this pull-request
1. There are still `fr_CA` files in:
   - es/webapp/src/main/webapp/templates/freemarker/body/partials/individual
1. There are still all language files in:
   - pt_BR/webapp/src/main/webapp/themes/tenderfoot/i18n/images

**Comment by UQAM-VIVO** [comment]
Terminer la suppression des fichiers

**Comment by awoods** [comment]
There appears to still be all language files in:
- pt_BR/webapp/src/main/webapp/themes/tenderfoot/i18n/images

**Comment by UQAM-VIVO** [comment]
Hope is the last removal :-)

**Pull request merged**
