### PR TITLE
Added initialTBoxAnnotations_fr_CA.nt

### PR DESCRIPTION
**Pull request by nicalico**
https://github.com/vivo-project/VIVO/pull/170 fix is not working with the fr_CA version of VIVO, due to missing file (see [comment](https://github.com/vivo-project/VIVO/pull/170#issuecomment-631772400)).

This PR is adding the necessary folder and file.

### CODE REVIEW

**Comment by awoods** [comment]
Resolves: https://jira.lyrasis.org/browse/VIVO-1880

**Comment by KarenRackham** [comment]
@awoods I used the file provided by Michel. I'll check this out on Monday morning.

**Comment by nicalico** [comment]
Sorry, message by KarenRackham was mine. I was on another machine, logged with other account.

**Comment by nicalico** [comment]
@awoods Commit 4006048 should fix it. I compiled it and made sure VIVO could start  up.

**Comment by nicalico** [comment]
PR was mistakenly closed while cleaning up.

**Pull request merged**
