### PR TITLE
Minor modifications in fr_CA RDF files 

### PR DESCRIPTION
**Pull request by nicalico**
Resolves second half of https://jira.lyrasis.org/browse/VIVO-1853

### CODE REVIEW

**Comment by wwelling** [comment]
I really need to update the parent task. I have completed this already as well.
https://github.com/vivo-project/VIVO-languages/pull/81/files

**Comment by wwelling** [comment]
I may have updated one that should not have.

https://github.com/vivo-project/VIVO-languages/pull/81/files#diff-b031282e50f38a90dc773640720dc6a1aa950b259e599f9d4c4aa84ee99d69ebR1778

I am no expert on this and you can close my PR if appropriate. :)

**Comment by nicalico** [comment]
Oh sorry -- my mistake. I thought both tickets were pointing to the same tab capitalization issue, but different rdf corrections. I went too fast.

**Comment by nicalico** [comment]
Your PR is flawless. Closing this one.

**Comment by wwelling** [comment]
It is rather inconvenient managing PRs across four repositories for a single issue.

**Pull request closed without merging**
