### PR TITLE
Bug 1863

### PR DESCRIPTION
**Pull request by MichelHeon**
Correcting Jira ticket [https://jira.lyrasis.org/browse/VIVO-1863](url) by moving labels ontologies from everytime directories to firsttime directories for all languages. Testing procedure will be in the ticket.

### CODE REVIEW

**Comment by awoods** [comment]
It appears that there are merge conflicts with this pull-request. Can you resolve the conflicts and put the JIRA back into "Review"?

**Comment by MichelHeon** [comment]
@awoods I don't have the writing rights to resolve this conflict.

**Comment by awoods** [comment]
@MichelHeon : When resolving merge conflicts, the idea is that you align your pull-request branch with what is in the `sprint-i81n` branch. For example:
```
git checkout sprint-i18n
git pull
git checkout Bug-1863
git rebase sprint-i18n
...resolve merge conflicts but fixing conflicting files...
git add <files that had conflicts>
git rebase --continue
git push MichelHeon
```

**Comment by MichelHeon** [comment]
@awoods that tells me it's up to date and there's no conflict.

**Comment by awoods** [comment]
At what point in the steps above does "it" say that there is no conflict?

**Comment by MichelHeon** [comment]
@awoods There is the trace of my commands
`$ git clone https://github.com/MichelHeon/VIVO-languages.git
Clonage dans 'VIVO-languages'...
remote: Enumerating objects: 111, done.
remote: Counting objects: 100% (111/111), done.
remote: Compressing objects: 100% (67/67), done.
remote: Total 1706 (delta 26), reused 95 (delta 10), pack-reused 1595
Réception d'objets: 100% (1706/1706), 795.01 KiB | 2.80 MiB/s, fait.
Résolution des deltas: 100% (495/495), fait.

Michel Heon@win-parfeau /cygdrive/c/UQAM-DEV/GIT/Bug-1863
$ cd VIVO-languages/

Michel Heon@win-parfeau /cygdrive/c/UQAM-DEV/GIT/Bug-1863/VIVO-languages
$ git checkout sprint-i18n
La branche 'sprint-i18n' est paramétrée pour suivre la branche distante 'sprint-i18n' depuis 'origin'.
Basculement sur la nouvelle branche 'sprint-i18n'

Michel Heon@win-parfeau /cygdrive/c/UQAM-DEV/GIT/Bug-1863/VIVO-languages
$ git pull
Déjà à jour.

Michel Heon@win-parfeau /cygdrive/c/UQAM-DEV/GIT/Bug-1863/VIVO-languages
$ git checkout Bug-1863
La branche 'Bug-1863' est paramétrée pour suivre la branche distante 'Bug-1863' depuis 'origin'.
Basculement sur la nouvelle branche 'Bug-1863'

Michel Heon@win-parfeau /cygdrive/c/UQAM-DEV/GIT/Bug-1863/VIVO-languages
$ git rebase sprint-i18n
La branche courante Bug-1863 est à jour.

Michel Heon@win-parfeau /cygdrive/c/UQAM-DEV/GIT/Bug-1863/VIVO-languages`

**Comment by MichelHeon** [comment]
At this command, git indicates that the rebase is up to date, there is no mention of conflict.
```
$ git rebase sprint-i18n
La branche courante Bug-1863 est à jour.
```

**Comment by awoods** [comment]
You are cloning your own `sprint-i18n` branch... which is significantly behind the upstream `sprint-i18n` branch.
https://github.com/MichelHeon/VIVO-languages/compare/sprint-i18n...vivo-project:sprint-i18n

You should first bring your `sprint-i18n` branch up to date with the upstream branch.
```
git remote add upstream https://github.com/vivo-project/VIVO-languages.git
git fetch upstream
git push origin upstream/sprint-i18n:sprint-i18n
```

**Comment by MichelHeon** [comment]
@awoods 
Are you sure the rest of these commands are working?
```
git checkout sprint-i18n
git pull
git checkout Bug-1863
git rebase sprint-i18n
...resolve merge conflicts but fixing conflicting files...
git add <files that had conflicts>
git rebase --continue
git push MichelHeon
```

**Comment by MichelHeon** [comment]
@awoods 
I have this response 
```
git checkout sprint-i18n
error: pathspec 'sprint-i18n' did not match any file(s) known to git.
```

**Comment by MichelHeon** [comment]
@awoods 
This is my trace
```
git clone https://github.com/MichelHeon/VIVO-languages
Cloning into 'VIVO-languages'...
remote: Enumerating objects: 214, done.
remote: Counting objects: 100% (214/214), done.
remote: Compressing objects: 100% (144/144), done.
remote: Total 1837 (delta 38), reused 165 (delta 11), pack-reused 1623
Receiving objects: 100% (1837/1837), 898.90 KiB | 3.71 MiB/s, done.
Resolving deltas: 100% (513/513), done.
heon@ubuntu:~/VIVO$ ls
VIVO-languages
heon@ubuntu:~/VIVO$ cd VIVO-languages/
heon@ubuntu:~/VIVO/VIVO-languages$ ls
home  pom.xml  README.md  update-versions.sh  vivo-rc-script-languages.sh  webapp
heon@ubuntu:~/VIVO/VIVO-languages$ git remote add upstream https://github.com/vivo-project/VIVO-languages.git^C
heon@ubuntu:~/VIVO/VIVO-languages$ ls
home  pom.xml  README.md  update-versions.sh  vivo-rc-script-languages.sh  webapp
heon@ubuntu:~/VIVO/VIVO-languages$ git remote add upstream https://github.com/vivo-project/VIVO-languages.git
heon@ubuntu:~/VIVO/VIVO-languages$ git fetch upstream
remote: Enumerating objects: 73, done.
remote: Counting objects: 100% (73/73), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 73 (delta 10), reused 63 (delta 9), pack-reused 0
Unpacking objects: 100% (73/73), done.
From https://github.com/vivo-project/VIVO-languages
 * [new branch]      add_zh-CH         -> upstream/add_zh-CH
 * [new branch]      gneissone-patch-1 -> upstream/gneissone-patch-1
 * [new branch]      master            -> upstream/master
 * [new branch]      rel-1.10-maint    -> upstream/rel-1.10-maint
 * [new branch]      rel-1.11.0-RC     -> upstream/rel-1.11.0-RC
 * [new branch]      rel-1.11.0-maint  -> upstream/rel-1.11.0-maint
 * [new branch]      rel-1.11.1-RC     -> upstream/rel-1.11.1-RC
 * [new branch]      rel-1.11.1-maint  -> upstream/rel-1.11.1-maint
 * [new branch]      sprint-i18n       -> upstream/sprint-i18n
 * [new branch]      v1.7-update       -> upstream/v1.7-update
heon@ubuntu:~/VIVO/VIVO-languages$ git push origin upstream/sprint-i18n:sprint-i18n
Username for 'https://github.com': michelheon
Password for 'https://michelheon@github.com': 
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/MichelHeon/VIVO-languages
   08e6a32..301aaa6  upstream/sprint-i18n -> sprint-i18n
heon@ubuntu:~/VIVO/VIVO-languages$ git checkout sprint-i18n
error: pathspec 'sprint-i18n' did not match any file(s) known to git.
```

**Comment by awoods** [comment]
Looks good. For your last command, try:
```
git checkout --track origin/sprint-i18n
```

**Comment by MichelHeon** [comment]
@awoods 
Now I have this 
```
git push MichelHeon
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push MichelHeon HEAD:<name-of-remote-branch>

```

**Comment by awoods** [comment]
```
git checkout master
git checkout --track origin/sprint-i18n
```
You should not be in a detached head after that.

**Comment by MichelHeon** [comment]
@awoods 
Now I have this...
Now I'm completely confused.

```
heon@ubuntu:~/VIVO/VIVO-languages$ git checkout master
Previous HEAD position was 301aaa6 [VIVO-1846] i18n: Added i18n support for Capability Map control buttons (#58)
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
heon@ubuntu:~/VIVO/VIVO-languages$ git checkout --track origin/sprint-i18n
fatal: A branch named 'sprint-i18n' already exists.
```

**Comment by awoods** [comment]
```
git branch -D sprint-i18n
git checkout --track upstream/sprint-i18n
git log
```
make sure commits match: https://github.com/vivo-project/VIVO-languages/commits/sprint-i18n

**Comment by awoods** [comment]
Superseded by: https://github.com/vivo-project/VIVO-languages/pull/62

**Pull request closed without merging**
