### PR TITLE
Remove unnecessary mentions of "One-time permisssion" from language files

### PR DESCRIPTION
**Pull request by hauschke**
Addresses https://jira.duraspace.org/browse/VIVO-1734 and some minor improved translations

### CODE REVIEW

**Comment by gneissone** [comment]
@hauschke It appears there are a lot of changes beyond the removal of the one-time permission language. Can you split these changes into separate pull requests (assuming you intend to propose the inclusion of the additional German language files, which would be great).

**Comment by hauschke** [comment]
@gneissone: I think the last commit was squashed(?), which means we have all those meaningless commits lie around.  These commits go a lot further back then what I did, that is true. 

I will try to find a way, but we should discuss how we generally deal with the language repositories. There will be more of them in the future, I think (and hope).

**Comment by awoods** [comment]
@hauschke : I would be very interested in discussing how we deal with language repositories going forward. Shall we do that in the #i18n VIVO Slack channel?

The idea that the @vivo-project/vivo-committers have been discussing is to consolidate the languages (including English) into VIVO/Vitro-languages, and include those dependencies in the VIVO build. In that scenario, all languages would be encouraged to have a place in VIVO/Vitro-Languages.

**Comment by hauschke** [comment]
Yes, let's move over to the I18N channel!

**Comment by awoods** [comment]
> @hauschke It appears there are a lot of changes beyond the removal of the one-time permission language. Can you split these changes into separate pull requests (assuming you intend to propose the inclusion of the additional German language files, which would be great).

@gneissone / @hauschke : Is it correct that the limited changes intended for this pull-request have not yet been teased apart?

**Comment by hauschke** [comment]
Correct. Mainly because I don't know how to do it in a way so I don't have to do it for every minor PR from the VIVO-DE repository.

**Comment by gneissone** [comment]
Changes specific to VIVO-1734 have been replicated in https://github.com/vivo-project/VIVO-languages/pull/77. Any additional improvements that were outside the original scope have presumably been addressed in subsequent i18n work, thus I am closing this pull request. Please let me know if that's not the case.

**Pull request closed without merging**
